[profile.default]
src = "src"
out = "dApp/src/generated/abis"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
extra_output = ["abi"]
extra_output_files = ["abi"]

remappings = [
    "@chainlink/contracts/=lib/foundry-chainlink-toolkit/lib/chainlink-brownie-contracts/contracts/src/",
    "@pythnetwork/pyth-sdk-solidity/=node_modules/@pythnetwork/pyth-sdk-solidity/"
]

[rpc_endpoints]
ink_sepolia = "https://rpc-gel-sepolia.inkonchain.com/"
eth_sepolia = "https://sepolia.infura.io/v3/${INFURA_API_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
